import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Navigation } from "./components/Navigation";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen items-center justify-center bg-black font-sans">
          <main className="flex min-h-screen w-full max-w-3xl flex-col items-center py-32 px-16 bg-black sm:items-start">
            <Navigation />
            <div className="flex flex-col items-center gap-6 text-center sm:items-start sm:text-left">
              {children}
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
